PutusanWeb/Controllers/PidanaController.cs
using Common;
using DataAccess;
using DataModel;
using PagedList;
using PutusanWeb.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Web.Mvc;

namespace PutusanWeb.Controllers
{
    public class PidanaController : Controller
    {
        private EntityContext db = new EntityContext();

        // GET: PidanaViewModels
        public ActionResult Index(string query, int page = 1, int pageSize = 10)
        {

            


            //ExtractJson extr = new ExtractJson();
            //extr.ReadJson();


            var model = new List<PidanaViewModel>();
            int count = 0;

            if (query != string.Empty)
            {
                try
                {

                    using (var context = new EntityContext())
                    {

                       
                        List<Common.Filter> filter = new List<Common.Filter>();
                        Common.Filter cF = null;

                        List<PutusanPidana> lrest = new List<PutusanPidana>();

                        if (query != null)
                        {
                            string[] param = query.Trim().Split(' ');
                            ViewBag.CurrentFilter = query;


                            /********************************************
                            * buat di local
                            ********************************************/

                            //foreach (string temp in param)
                            //{
                            //    cF = new Common.Filter();
                            //    cF.Value = temp.ToLower();
                            //    cF.PropertyName = "Raw";
                            //    cF.Operation = Op.Contains;
                            //    filter.Add(cF);
                            //}

                            //var deleg = Helper.ExpressionBuilder.GetExpression<PutusanPidana>(filter).Compile();
                            //lrest = context.PutusanPidanas.Where(deleg)
                            //    .OrderByDescending(x => x.TanggalDibacakan)
                            //    .Skip((page - 1) * pageSize)
                            //    .Take(pageSize).ToList();

                            //count = context.PutusanPidanas.Where(deleg).Count();



                            /************************************************
                             *  end buat dii local
                             * ***************************************/




                            /********************************************
                             * buat di server
                             ********************************************/
                            var values = new StringBuilder();
                            values.AppendFormat("{0}", param[0]);
                            for (int i = 1; i < param.Length; i++)
                                values.AppendFormat(" and {0}", param[i]);

                            var sql = string.Format(
                            "SELECT * FROM PutusanPidanas WHERE  CONTAINS ([Raw],   '{0}')", values);


                            //lrest = context.Set<PutusanPidana>().SqlQuery(sql).Take(100).ToList();

                            lrest = context.Set<PutusanPidana>().SqlQuery(sql)
                                .OrderByDescending(x => x.TanggalDibacakan)
                                .Skip((page - 1) * pageSize)
                                .Take(pageSize).ToList();

                            count = context.Set<PutusanPidana>().SqlQuery(sql).Count();

                            /************************************************
                             *  end buar server
                             * ***************************************/




                        }
                        else
                        {
                            lrest = context.PutusanPidanas.OrderByDescending(x => x.TanggalDibacakan)
                                .Skip((page - 1) * pageSize)
                                .Take(pageSize).ToList();

                            count = context.PutusanPidanas.Count();
                        }

                        //var value = context.PutusanPidanas.Where(x => x.CatatanAmar.Contains()).ToList();

                        foreach (var employee in lrest)
                        {
                            var empModel = new PidanaViewModel();
                            empModel.ID = employee.ID;
                            empModel.NomorPutusan = employee.NomorPutusan;
                            empModel.Penuntut = employee.Penuntut;
                            empModel.Amar = employee.Amar;
                            empModel.TanggalRegister = employee.TanggalRegister;
                            empModel.TanggalDibacakan = employee.TanggalDibacakan;
                            empModel.CatatanAmar = employee.CatatanAmar;
                            empModel.Klasifikasi = employee.Klasifikasi;
                            //if (employee.HakimKetua != null)
                            //{
                            //    empModel.HakimKetua = employee.HakimKetua;
                            //}
                            //empModel.LembagaPeradilan = employee.Peradilan.Nama;
                            //employee.HakimAnggota.ToList()[0].Nama
                            //empModel.CatatanAmar = employee.IsEmployeeRetired ? "Yes" : "No";
                            model.Add(empModel);
                        }
                    }
                }
                catch (Exception ex)
                {

                    throw;
                }
            }

            var resultAsPagedList = new StaticPagedList<PidanaViewModel>(model, page, pageSize, count);

            return View(resultAsPagedList);
          
        }


        public string addLink(string data)
        {
            //string link = HtmlHelper.GenerateLink(this.ControllerContext.RequestContext, System.Web.Routing.RouteTable.Routes, "My link", "Default", "About", "Home", null, null);

            string link = "test <br/>";

            //string link = "<a href='" + Url.Action("PutusanPidanas", "Details", new { id = 1 }, null) + "><span>Edit Group</span></a>";
            //StringBuilder sb = new StringBuilder();
            //sb.AppendLine(link);
            //sb.AppendLine(data);
           
           
           data = link + data;
            return data;
        }
       

        //[HttpGet]
        //public ActionResult Search()
        //{
        //    return PartialView("_SearchFormPartial");
        //}

        

       
    }
}

PutusanWeb/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccess;
using DataModel;
using PagedList;

namespace PutusanWeb.Controllers
{
    public class SharedController : Controller
    {
        private EntityContext db = new EntityContext();


        //[ChildActionOnly]
        public ActionResult Index(string pnid)
        {
            DDModel mod = new DDModel();
            List<int> yea = new List<int>();
            List<SelectListItem> list = new List<SelectListItem>();
            SelectListItem item = null;
            for (int i =0; i < 10; i ++)
            {
                item = new SelectListItem();
                int ye = DateTime.Now.Year - i;
                yea.Add(ye);
                item.Value = ye.ToString();
                item.Text = ye.ToString();
                list.Add(item);
            }
            mod.Year = yea;
            mod.YearList = new SelectList(list, "Value", "Text"); 
            
            //List<ChartDetail> lCD = new List<ChartDetail>();
            TempData["pnid"] = pnid;
            return PartialView("_ListPutusanStat", mod);
        }

        //public ActionResult Index(int? page)
        //{
        //    var listPaged = page.ToString();//GetPagedNames(page); // GetPagedNames is found in BaseController
        //    if (listPaged == null)
        //        return HttpNotFound();

        //    ViewBag.Names = listPaged;
        //    return Request.IsAjaxRequest()
        //        ? (ActionResult)PartialView("_ListPutusanStat")
        //        : View();
        //}


        public ActionResult DaftarPutusan(string pengadilanID = "", int page = 1, int pageSize = 15, string hakimID = "" )
        {

            var model = new List<PutusanPidana>();
            int  count = 0;
            int id;

            if (pengadilanID != string.Empty)
            {
                id = Convert.ToInt32(pengadilanID);

                count = db.PutusanPidanas.Where(x => x.PeradilanID == id).Count();
                model = db.PutusanPidanas.Where(x => x.PeradilanID == id)
                             .OrderByDescending(x => x.TanggalDibacakan)
                             .Skip((page - 1) * pageSize)
                             .Take(pageSize).ToList();

                ViewBag.Pengadilan = pengadilanID;
            }
            else if (hakimID != string.Empty)
            {
                id = Convert.ToInt32(hakimID);
                
                count = db.PutusanPidanas.Where(x => x.HakimKetuaID == id).Count();
                model = db.PutusanPidanas.Where(x => x.HakimKetuaID == id)
                             .OrderByDescending(x => x.TanggalDibacakan)
                             .Skip((page - 1) * pageSize)
                             .Take(pageSize).ToList();

                ViewBag.Hakim = hakimID;
            }

            var resultAsPagedList = new StaticPagedList<PutusanPidana>(model, page, pageSize, count);

            return PartialView("ListPutusan", resultAsPagedList);
            //return PartialView("ListPutusan", model.ToPagedList(page, pageSize));

            //return View("ListPutusan.cshtml", model.ToPagedList(page, pageSize));
        }

        [HttpPost]
        public JsonResult RetrieveStatistic()
        {
            return getStatistics("");
        }


        [HttpPost]
        public JsonResult FilterStatistic(string year)
        {
           
            return  getStatistics(year);
        }

        public JsonResult  getStatistics(string year)
        {
            int id = Convert.ToInt16(TempData["pnid"]);
           
               DateTime end = new DateTime(DateTime.Now.Year, 12, 31);
               DateTime start = new DateTime(DateTime.Now.Year, 1, 1);
            
            if (year != string.Empty )
            {
                 end = new DateTime(Convert.ToInt32(year), 12, 31);
                 start = new DateTime(Convert.ToInt32(year), 1, 1);
            }


            List<PutusanPidana> lPutusan = db.PutusanPidanas.Where(x => x.TanggalDibacakan <= end && x.TanggalDibacakan >= start && x.PeradilanID == id).ToList();
            List<PutusanPidana> lPutusanTemp = lPutusan.GroupBy(x => x.SubKlasifikasi).Select(x => x.First()).ToList();
            List<ChartDetail> lC = new List<ChartDetail>();
            ChartDetail cd = null;
            Random random = new Random();
            for (int i = 0; i < lPutusanTemp.Count; i++)
            {
                cd = new ChartDetail();

                cd.JumlahPutusan = lPutusan.Where(x => x.SubKlasifikasi == lPutusanTemp[i].SubKlasifikasi).ToList().Count;
                cd.SubKlasifikasi = lPutusanTemp[i].SubKlasifikasi;
                cd.Tahun = i.ToString();
                lC.Add(cd);

            }
            TempData["pnid"] = id;
            return Json(lC.OrderByDescending(x => x.JumlahPutusan));
        }
       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public class ChartDetail
        {
            public string Tahun { get; set; }
            public string Klasifikasi { get; set; }
            public string SubKlasifikasi { get; set; }
            public int JumlahPutusan { get; set; }
        }

      
    }
}

PutusanWeb/Controllers/UndangUndangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccess;
using DataModel;

namespace PutusanWeb.Controllers
{
    public class UndangUndangsController : Controller
    {
        private EntityContext db = new EntityContext();

        // GET: UndangUndangs
        public ActionResult Index()
        {
            return View(db.UndangUndangs.ToList());
        }

        // GET: UndangUndangs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UndangUndang undangUndang = db.UndangUndangs.Find(id);
            if (undangUndang == null)
            {
                return HttpNotFound();
            }
            return View(undangUndang);
        }

        public ActionResult QueryDetails(string query, string type)
        {


            JenisUndangUndang jenisuu = (JenisUndangUndang)Enum.Parse(typeof(JenisUndangUndang), type);
            UndangUndang undangUndang = db.UndangUndangs.Where(x => x.PasalKompak == query && x.JenisUU == jenisuu).FirstOrDefault();

            //if (undangUndang != null)
            //{
            //    undangUndang.TextPasal = undangUndang.TextPasal.Replace(".",  System.Environment.NewLine);
                
            //}
           

            //UndangUndang undangUndang = null;

            return View("Details", undangUndang);
        }


        // GET: UndangUndangs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UndangUndangs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Pasal,TextPasal,JenisUU,HukumanPenjara")] UndangUndang undangUndang)
        {
            if (ModelState.IsValid)
            {
                db.UndangUndangs.Add(undangUndang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(undangUndang);
        }

        // GET: UndangUndangs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UndangUndang undangUndang = db.UndangUndangs.Find(id);
            if (undangUndang == null)
            {
                return HttpNotFound();
            }
            return View(undangUndang);
        }

        // POST: UndangUndangs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Pasal,TextPasal,JenisUU,HukumanPenjara")] UndangUndang undangUndang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(undangUndang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(undangUndang);
        }

        // GET: UndangUndangs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UndangUndang undangUndang = db.UndangUndangs.Find(id);
            if (undangUndang == null)
            {
                return HttpNotFound();
            }
            return View(undangUndang);
        }

        // POST: UndangUndangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UndangUndang undangUndang = db.UndangUndangs.Find(id);
            db.UndangUndangs.Remove(undangUndang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PutusanWeb/Views/Shared/ListPutusan.cshtml
@*@model IEnumerable<DataModel.PutusanPidana>*@

@model PagedList.IPagedList<DataModel.PutusanPidana>
@using PagedList.Mvc



@if (Model.Count() > 0)
{
    <div id="divPutusan">
        <div>
            <table class="table table-striped">
                <tr>

                    <th>
                        Nomor Putusan
                        @*@Html.DisplayNameFor(model => model.NomorPutusan)*@
                    </th>

                    <th>
                        Tanggal Dibacakan
                        @*@Html.DisplayNameFor(model => model.TanggalDibacakan)*@
                    </th>


                </tr>

                @foreach (var item in Model)
        {
        <tr>

            <td>
                @Html.ActionLink(item.NomorPutusan, "Details", "PutusanPidanas", new { id = item.ID }, null)
                @*@Html.DisplayFor(modelItem => item.NomorPutusan)*@
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.TanggalDibacakan)
            </td>


        </tr>
        }

            </table>
        </div>
        <div>

            @Html.PagedListPager(Model, page => Url.Action("DaftarPutusan", "Shared", new { pengadilanID = ViewBag.Pengadilan, page, pageSize = Model.PageSize, hakimID = ViewBag.Hakim }),
           PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new PagedListRenderOptions() { MaximumPageNumbersToDisplay = 3, DisplayEllipsesWhenNotShowingAllPageNumbers = false}, new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "divPutusan" }))


            Showing @Model.FirstItemOnPage to @Model.LastItemOnPage of @Model.TotalItemCount Records


        </div>
    </div>
}


@*@Html.Code(@<div>
        @@(Html.BootstrapTable(Url.Action("GetPeopleData"))
        .Columns("Id", "FirstName", "LastName", "Email")
        )
    </div>)
<br />
@(Html.BootstrapTable(Url.Action("GetPeopleData"))
    .Columns("Id", "FirstName", "LastName", "Email")
)*@

PutusanWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Indojustice Portal</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
   

    <script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function i(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s="AuthenticatedUserContext",h="start",c="stop",l="Track",a=l+"Event",v=l+"Page",y=u.createElement(o),r,f;y.src=config.url||"https://az416426.vo.msecnd.net/scripts/a/ai.0.js";u.getElementsByTagName(o)[0].parentNode.appendChild(y);try{t.cookie=u.cookie}catch(p){}for(t.queue=[],t.version="1.0",r=["Event","Exception","Metric","PageView","Trace","Dependency"];r.length;)i("track"+r.pop());return i("set"+s),i("clear"+s),i(h+a),i(c+a),i(h+v),i(c+v),i("flush"),config.disableExceptionTracking||(r="onerror",i("_"+r),f=e[r],e[r]=function(config,i,u,e,o){var s=f&&f(config,i,u,e,o);return s!==!0&&t["_"+r](config,i,u,e,o),s}),t
        }({
            instrumentationKey:"369c927c-ad4c-4719-a642-d8b5a76afc0e"
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Indojustice", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @*<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>*@
        @*</div>
    </div>*@
    <div class="navbar navbar-default navbar-fixed-top" role="navigation" id="navbar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand scrollTo" href="@Url.Action("Index", "Pidana" )">Indojustice</a>
            </div>
            <div class="navbar-collapse collapse" id="navigation">
                <ul class="nav navbar-nav navbar-right">
                    @*<li class="active">
                        <a href="#intro">Home</a>
                    </li>
                    <li>
                        <a href="#about">About</a>
                    </li>
                    <li>
                        <a href="#services">Services</a>
                    </li>*@
                    <!--<li><a href="#testimonials">Testimonials</a>
                    </li>-->
                    @*<li>
                        <a href="#references">Our work</a>
                    </li>
                    <li>
                        <a href="#customers">Clients</a>
                    </li>
                    <li>
                        <a href="#contact">Contact</a>
                    </li>*@

                    <!--<li class="dropdown">
                        <a href="http://localhost:63180/pilkadadki.html#pilkada" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Our Project<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="http://localhost:63180/pilkadadki.html#pilkada">Pilkada DKI</a>
                            </li>


                        </ul>
                    </li>-->

                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
    <div class="container">
        <br />
        <br />
        <br />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Indojustice</p>
        </footer>
    </div>

  
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>

PutusanWeb/Views/Shared/_ListPutusanStat.cshtml
@model DataModel.DDModel

<div id="divPutStat" class="well">
    
    <div class="row form-group">

        <div class="col-md-2"><strong>Pilih Tahun</strong></div>

        <div class="col-lg-9">
            @Html.DropDownListFor(m => m.ID, Model.YearList, new { @class = "form-control", @onchange = "reDrawChart();" })
        </div>
    </div>

    <div class="row ">
        <div id="chart" style="width: 100%; height: 400px;">
        </div>
    </div>
    </div>

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
        google.load("visualization", "1", { packages: ["corechart"] });
        //google.setOnLoadCallback(drawChart);
        $(function () {
            $.ajax({
                type: "POST",
                url: "/Shared/RetrieveStatistic",
                data: '{}',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (r) {


                    drawPieChart(r); // calling method


                },
                failure: function (r) {
                    alert(r.d);
                },
                error: function (r) {
                    alert(r.d);
                }
            });
        })

        function drawPieChart(dataValues) {

            var data = new google.visualization.DataTable();


            data.addColumn('string', 'Sub Klasifikasi');
            data.addColumn('number', 'Jumlah Putusan');
            data.addColumn({ type: 'number', role: 'annotation' });


            for (var i = 0; i < dataValues.length; i++) {
                data.addRow([dataValues[i].SubKlasifikasi, dataValues[i].JumlahPutusan, dataValues[i].JumlahPutusan]);
            }
            //data.addRow([null, null, 30]);
            // Instantiate and draw our chart, passing in some options
            var chart = new google.visualization.BarChart(document.getElementById('chart'));
            var formatter = new google.visualization.NumberFormat({ pattern: '#,###.00' });

            var options = {
                //title: 'Correlation between life expectancy, fertility rate ' +
                //       'and population of some world countries (2010)',

                //title: "Jumlah kasus per tahun yang diadili",
                position: "top",
                fontsize: "14px",
                chartArea: { width: '75%', height:"95%" },
                //seriesType: "bars",
                //series: { 2: { type: "line", color: 'black' } },
                backgroundColor: "none",
                vAxis: {
                    gridlines: {
                        color: 'transparent'
                    },
                    //textPosition: 'none',
                    baselineColor: 'transparent'
                },
                hAxis: {

                    gridlines: {
                        color: 'transparent'
                    },
                    textPosition: 'none'
                },
                legend: 'none',
                colors: ['#009688', '#009688', '#009688']
            };

            chart.draw(data, options);
        }

        function reDrawChart() {
            //alert('masuk');

            var yearID = $('#ID').val() || [];

            //alert(yearID);

            $.ajax({
                type: "POST",
                url: "/Shared/FilterStatistic",
                data: JSON.stringify({
                    year: yearID.toString(), locale: 'en-US'
                }),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (r) {

                    //alert(r);
                    drawPieChart(r); // calling method

                    //var data = google.visualization.arrayToDataTable(r);

                    ////Pie
                    //var options = {
                    //    title: 'Putusan yang sudah dibuat'
                    //};
                    //var chart = new google.visualization.PieChart($("#chart")[0]);
                    //chart.draw(data, options);
                },
                failure: function (r) {
                    alert(r.d);
                },
                error: function (r) {
                    alert(r.d);
                }
            });
        }
    </script>

PutusanWeb/Views/Shared/_UndangUndang.cshtml
@model IEnumerable<DataModel.UndangUndang>



    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pasal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TextPasal)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.JenisUU)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HukumanPenjara)
            </th>*@
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Pasal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TextPasal)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.JenisUU)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HukumanPenjara)
                </td>*@
                
            </tr>
        }

    </table>

   