PutusanWeb/Controllers/PidanaController.cs
using Common;
using DataAccess;
using DataModel;
using PagedList;
using PutusanWeb.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Web.Mvc;

namespace PutusanWeb.Controllers
{
    public class PidanaController : Controller
    {
        private EntityContext db = new EntityContext();

        // GET: PidanaViewModels
        public ActionResult Index(string query, int page = 1, int pageSize = 10)
        {

            


            //ExtractJson extr = new ExtractJson();
            //extr.ReadJson();


            var model = new List<PidanaViewModel>();
            int count = 0;

            if (query != string.Empty)
            {
                try
                {

                    using (var context = new EntityContext())
                    {

                       
                        List<Common.Filter> filter = new List<Common.Filter>();
                        Common.Filter cF = null;

                        List<PutusanPidana> lrest = new List<PutusanPidana>();

                        if (query != null)
                        {
                            string[] param = query.Trim().Split(' ');
                            ViewBag.CurrentFilter = query;


                            /********************************************
                            * buat di local
                            ********************************************/

                            //foreach (string temp in param)
                            //{
                            //    cF = new Common.Filter();
                            //    cF.Value = temp.ToLower();
                            //    cF.PropertyName = "Raw";
                            //    cF.Operation = Op.Contains;
                            //    filter.Add(cF);
                            //}

                            //var deleg = Helper.ExpressionBuilder.GetExpression<PutusanPidana>(filter).Compile();
                            //lrest = context.PutusanPidanas.Where(deleg)
                            //    .OrderByDescending(x => x.TanggalDibacakan)
                            //    .Skip((page - 1) * pageSize)
                            //    .Take(pageSize).ToList();

                            //count = context.PutusanPidanas.Where(deleg).Count();



                            /************************************************
                             *  end buat dii local
                             * ***************************************/




                            /********************************************
                             * buat di server
                             ********************************************/
                            var values = new StringBuilder();
                            values.AppendFormat("{0}", param[0]);
                            for (int i = 1; i < param.Length; i++)
                                values.AppendFormat(" and {0}", param[i]);

                            var sql = string.Format(
                            "SELECT * FROM PutusanPidanas WHERE  CONTAINS ([Raw],   '{0}')", values);


                            //lrest = context.Set<PutusanPidana>().SqlQuery(sql).Take(100).ToList();

                            lrest = context.Set<PutusanPidana>().SqlQuery(sql)
                                .OrderByDescending(x => x.TanggalDibacakan)
                                .Skip((page - 1) * pageSize)
                                .Take(pageSize).ToList();

                            count = context.Set<PutusanPidana>().SqlQuery(sql).Count();

                            /************************************************
                             *  end buar server
                             * ***************************************/




                        }
                        else
                        {
                            lrest = context.PutusanPidanas.OrderByDescending(x => x.TanggalDibacakan)
                                .Skip((page - 1) * pageSize)
                                .Take(pageSize).ToList();

                            count = context.PutusanPidanas.Count();
                        }

                        //var value = context.PutusanPidanas.Where(x => x.CatatanAmar.Contains()).ToList();

                        foreach (var employee in lrest)
                        {
                            var empModel = new PidanaViewModel();
                            empModel.ID = employee.ID;
                            empModel.NomorPutusan = employee.NomorPutusan;
                            empModel.Penuntut = employee.Penuntut;
                            empModel.Amar = employee.Amar;
                            empModel.TanggalRegister = employee.TanggalRegister;
                            empModel.TanggalDibacakan = employee.TanggalDibacakan;
                            empModel.CatatanAmar = employee.CatatanAmar;
                            empModel.Klasifikasi = employee.Klasifikasi;
                            //if (employee.HakimKetua != null)
                            //{
                            //    empModel.HakimKetua = employee.HakimKetua;
                            //}
                            //empModel.LembagaPeradilan = employee.Peradilan.Nama;
                            //employee.HakimAnggota.ToList()[0].Nama
                            //empModel.CatatanAmar = employee.IsEmployeeRetired ? "Yes" : "No";
                            model.Add(empModel);
                        }
                    }
                }
                catch (Exception ex)
                {

                    throw;
                }
            }

            var resultAsPagedList = new StaticPagedList<PidanaViewModel>(model, page, pageSize, count);

            return View(resultAsPagedList);
          
        }


        public string addLink(string data)
        {
            //string link = HtmlHelper.GenerateLink(this.ControllerContext.RequestContext, System.Web.Routing.RouteTable.Routes, "My link", "Default", "About", "Home", null, null);

            string link = "test <br/>";

            //string link = "<a href='" + Url.Action("PutusanPidanas", "Details", new { id = 1 }, null) + "><span>Edit Group</span></a>";
            //StringBuilder sb = new StringBuilder();
            //sb.AppendLine(link);
            //sb.AppendLine(data);
           
           
           data = link + data;
            return data;
        }
       

        //[HttpGet]
        //public ActionResult Search()
        //{
        //    return PartialView("_SearchFormPartial");
        //}

        

       
    }
}

PutusanWeb/Controllers/PutusanPidanasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccess;
using DataModel;
using System.Reflection;
using System.Text;
using Common;
using System.Web.Mvc.Html;


namespace PutusanWeb.Controllers
{
    public class PutusanPidanasController : Controller
    {
        private EntityContext db = new EntityContext();

        // GET: PutusanPidanas
        public ActionResult Index()
        {
            var putusanPidanas = db.PutusanPidanas.Include(p => p.HakimKetua).Include(p => p.Penuntut);
            return View(putusanPidanas.ToList());
        }

        // GET: PutusanPidanas/Details/5

        public ActionResult Details(int? id = 3637)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            //int nomor = Convert.ToInt32(id);
            PutusanPidana putusanPidana = db.PutusanPidanas.Where(x => x.ID == id).Include(o => o.HakimKetua).Include(x => x.Peradilan).Include(x => x.DataDetail).FirstOrDefault();
            if (putusanPidana == null)
            {
                return HttpNotFound();
            }

            if (putusanPidana.CatatanAmar != null)
            {
                putusanPidana.CatatanAmar = putusanPidana.CatatanAmar.Replace(";", ";" + System.Environment.NewLine);
                putusanPidana.CatatanAmar = putusanPidana.CatatanAmar.Replace("M E N G A D I L I", "M E N G A D I L I " + System.Environment.NewLine);
                putusanPidana.CatatanAmar = putusanPidana.CatatanAmar.Replace("--", "");

                
            } 
            if(putusanPidana.Tersangka != null)
            {
                putusanPidana.Tersangka = putusanPidana.Tersangka.Replace("-", " ");
            }
            if (putusanPidana.Anggota != null)
            {
                putusanPidana.Anggota = putusanPidana.Anggota.Replace("-", " ");
            }
            //putusanPidana.CatatanAmar = putusanPidana.CatatanAmar.Replace(";", "<br />");
           
            //putusanPidana.Amar = link+" " + putusanPidana.Amar;

           

           // var a = "Email is locked, click " +
           //ControllerHtml.Html(this).Hyperlink("www.google.com", "unlock").ToString();

            //putusanPidana.CatatanAmar = InsertLinkforUU(putusanPidana.CatatanAmar);

            //if (putusanPidana.DataDetail != null)
            //{
            //    putusanPidana.DataDetail.TextPutusan = InsertLinkforUU(putusanPidana.DataDetail.TextPutusan);
            //}


            return View(putusanPidana);
        }

     
        public ActionResult DependentDetails(string query)
        {
            //int id = 51;

            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}

            byte[] data = Convert.FromBase64String(query);
            string decodedString = Encoding.UTF8.GetString(data).Trim();
            decodedString = Helper.fixNameCompact(Helper.fixPutusanNumber(decodedString));

            //int nomor = Convert.ToInt32(id);
            //PutusanPidana putusanPidana = db.PutusanPidanas.Where(x => x.ID == id).Include(o => o.HakimKetua).FirstOrDefault();


            PutusanPidana putusanPidana = db.PutusanPidanas.Where(x => x.NomorPutusanCompact == decodedString).Include(o => o.HakimKetua).Include(x => x.Peradilan).Include(x => x.DataDetail).FirstOrDefault();
            if (putusanPidana == null)
            {
                return View("Details", null);
            }

            if (putusanPidana.CatatanAmar != null)
            {
                putusanPidana.CatatanAmar = putusanPidana.CatatanAmar.Replace(";", ";" + System.Environment.NewLine);
                putusanPidana.CatatanAmar = putusanPidana.CatatanAmar.Replace("M E N G A D I L I", "M E N G A D I L I " + System.Environment.NewLine);
                putusanPidana.CatatanAmar = putusanPidana.CatatanAmar.Replace("--", "");
            }
            //putusanPidana.CatatanAmar = putusanPidana.CatatanAmar.Replace(";", "<br />");

            return View("Details", putusanPidana);
        }


        public ActionResult GetUndangUndang(string query= "penipuan")
        {

            List<UndangUndang> lUndangs = db.UndangUndangs.Where(x => x.TextPasal.Contains(query)).ToList();
            

            return PartialView("_UndangUndang", lUndangs);
        }


        // GET: PutusanPidanas/Create 
        public ActionResult Create()
        {
            ViewBag.HakimKetuaID = new SelectList(db.PenegakHukums, "ID", "Catatan");
            ViewBag.PenuntutID = new SelectList(db.PenegakHukums, "ID", "Catatan");
            return View();
        }

        // POST: PutusanPidanas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,NomorPutusan,Proses,TanggalRegister,TanggalMusyawarah,TanggalDibacakan,Klasifikasi,SubKlasifikasi,Panitera,JenisLembagaPeradilan,LembagaPeradilan,Tersangka,Amar,CatatanAmar,HakimKetuaID,Anggota,PenuntutID,Yurisprudensi,StatusTahanan,BerkekuatanHukumTetap,Kaidah,Ringkasan,Raw")] PutusanPidana putusanPidana)
        {
            if (ModelState.IsValid)
            {
                db.PutusanPidanas.Add(putusanPidana);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.HakimKetuaID = new SelectList(db.PenegakHukums, "ID", "Catatan", putusanPidana.HakimKetuaID);
            ViewBag.PenuntutID = new SelectList(db.PenegakHukums, "ID", "Catatan", putusanPidana.PenuntutID);
            return View(putusanPidana);
        }

        // GET: PutusanPidanas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PutusanPidana putusanPidana = db.PutusanPidanas.Find(id);
            if (putusanPidana == null)
            {
                return HttpNotFound();
            }
            ViewBag.HakimKetuaID = new SelectList(db.PenegakHukums, "ID", "Catatan", putusanPidana.HakimKetuaID);
            ViewBag.PenuntutID = new SelectList(db.PenegakHukums, "ID", "Catatan", putusanPidana.PenuntutID);
            return View(putusanPidana);
        }

        // POST: PutusanPidanas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,NomorPutusan,Proses,TanggalRegister,TanggalMusyawarah,TanggalDibacakan,Klasifikasi,SubKlasifikasi,Panitera,JenisLembagaPeradilan,LembagaPeradilan,Tersangka,Amar,CatatanAmar,HakimKetuaID,Anggota,PenuntutID,Yurisprudensi,StatusTahanan,BerkekuatanHukumTetap,Kaidah,Ringkasan,Raw")] PutusanPidana putusanPidana)
        {
            if (ModelState.IsValid)
            {
                db.Entry(putusanPidana).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.HakimKetuaID = new SelectList(db.PenegakHukums, "ID", "Catatan", putusanPidana.HakimKetuaID);
            ViewBag.PenuntutID = new SelectList(db.PenegakHukums, "ID", "Catatan", putusanPidana.PenuntutID);
            return View(putusanPidana);
        }

        // GET: PutusanPidanas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PutusanPidana putusanPidana = db.PutusanPidanas.Find(id);
            if (putusanPidana == null)
            {
                return HttpNotFound();
            }
            return View(putusanPidana);
        }

        // POST: PutusanPidanas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PutusanPidana putusanPidana = db.PutusanPidanas.Find(id);
            db.PutusanPidanas.Remove(putusanPidana);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //public static MvcHtmlString DisplayWithBreaksFor<TModel, TValue>(this HtmlHelper<TModel> html, Expression<Func<TModel, TValue>> expression)
        //{
        //    var metadata = ModelMetadata.FromLambdaExpression(expression, html.ViewData);
        //    var model = html.Encode(metadata.Model).Replace("\r\n", "<br />\r\n");

        //    if (String.IsNullOrEmpty(model))
        //        return MvcHtmlString.Empty;

        //    return MvcHtmlString.Create(model);
        //}

        public string fixLongSentence(string data)
        {

            string res = "";
            string restbefore = "";
            data = data.ToLower();
            int index = data.IndexOf(".");

            int n;
            

            while (index >= 0)
            {

                res = data.Substring(index, 1);
                restbefore = data.Substring(index-2, 1);
                //bool isNumeric = int.TryParse(restbefore, out n);
                if (res != " " && restbefore == ".")
                {
                    data = data.Insert(index + 1, System.Environment.NewLine);
                }



                index = data.IndexOf(".", index + 1);

PutusanWeb/Views/Pidana/Index.cshtml
@model PagedList.IPagedList<PutusanWeb.Models.PidanaViewModel>
@using PagedList.Mvc

@{
    ViewBag.Title = "Daftar Putusan";
}


<div class="row">
    <div class="col-md-12">


        <div class="mb20 text-center">
            <h2 class="title" data-animate="fadeInUp">Cari Putusan</h2>

        </div>

        @using (Html.BeginForm("Index", "Pidana", FormMethod.Get))
        {

            <div class=" row form-group">
                <div class="col-md-10 text-center" style=" padding:5px">
                    @Html.TextBox("query", ViewBag.CurrentFilter as string, new { @class = "form-control col-md-10" })
                </div>

                <div class="col-md-2 text-center" style=" padding:5px">

                    <button class="btn btn-success" type="submit">
                        <i class="glyphicon glyphicon-search" aria-hidden="true"></i> Search
                    </button>
                </div>
                @*<div class="row text-center col-md-12">
                    <span style="font-size:11px"> Kami hanya menampilkan 100 data hasil pencarian. Silakan menambahkan kata kata pencarian yang lebih spesifik untuk mendapatkan hasil yang lebih tepat seperti " <strong>bukittinggi judi 2016 </strong>" </span>
                </div>*@
            </div>

        }

        <br />
        <br />
        <br />



        <div id="search-results" class=" row ">

            @if (Model.Count() > 0)
        {




        <div>

            <table class="table table-striped">


                @foreach (var item in Model)
                {
            <tr>

                <td>
                    <div class="row col-md-12 ">
                        <h4 class="text-warning te">
                            Nomor Putusan :
                            @Html.ActionLink(item.NomorPutusan, "Details", "PutusanPidanas", new { id = item.ID }, null)
                        </h4>

                    </div>
                    <div class="row col-md-12">
                        Tanggal dibacakan:
                        @Html.DisplayFor(modelItem => item.TanggalDibacakan)

                    </div>
                    <div class="row col-md-12">
                        Klasifikasi:
                        @Html.DisplayFor(modelItem => item.Klasifikasi)

                    </div>
                    <div class="row col-sm-12 ">
                        <p class="well-sm">
                            @if (item.CatatanAmar != null && item.CatatanAmar.Length > 200)
                                    {
                                @Html.DisplayFor(modelItem => item.CatatanAmar).ToString().Substring(0, 200)
                                    }
                                    else
                                    {
                                @Html.DisplayFor(modelItem => item.CatatanAmar)
                                    }
                        </p>
                    </div>


                </td>


            </tr>
                }

            </table>

        </div>

        <div>
            @Html.PagedListPager(Model, page => Url.Action("Index", new { query = ViewBag.CurrentFilter, page, pageSize = Model.PageSize }), new PagedListRenderOptions { MaximumPageNumbersToDisplay = 3,  DisplayEllipsesWhenNotShowingAllPageNumbers = false })
            Showing @Model.FirstItemOnPage to @Model.LastItemOnPage of @Model.TotalItemCount Records

            @*@Html.PagedListPager(Model, page => Url.Action("Index", new { query = ViewBag.CurrentFilter, page, pageSize = Model.PageSize }),
                   PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new PagedListRenderOptions() { MaximumPageNumbersToDisplay = 3, DisplayEllipsesWhenNotShowingAllPageNumbers = false }, new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "search-results" }))
                Showing @Model.FirstItemOnPage to @Model.LastItemOnPage of @Model.TotalItemCount Records*@

        </div>

    }
    else
    {
        <p>
            No record found
        </p>
    }
        </div>

    </div>



</div>

<br />
<br />
<br />
<br />
<br />
<br />

PutusanWeb/Views/Pidana/_SearchResultsPartial.cshtml
@*//@model List<PutusanWeb.Models.PidanaViewModel>*@
@model PagedList.IPagedList <PutusanWeb.Models.PidanaViewModel>
@using PagedList.Mvc

@*@{
    ViewBag.Title = "Index";
}*@

<br />


@if (Model.Count() > 0) {

<div>
    <h2>Daftar Putusan</h2>

</div>

<div>

    <p>
        @*@Html.ActionLink("Create New", "Create")*@
    </p>


    <table class="table">
        <tr>
            <th>
                Nomor Putusan
            </th>
            <th>
                Terdakwa
            </th>
            <th>
                Keputusan
            </th>
            <th>
                Tanggal Putusan
            </th>
            <th>
                Hakim Ketua
            </th>
            <th>
                Penuntut
            </th>
            <th>
                Catatan Amar
            </th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.NomorPutusan, "SendCustomerMessage", "SendMessage",
                     new { id = item.NomorPutusan })
                    @*@Html.DisplayFor(modelItem => item.NomorPutusan)*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tergugat)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Kaidah)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TanggalRegister)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HakimKetua.Nama)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Penuntut.Nama)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CatatanAmar)
                </td>
            </tr>
        }

    </table>

    <br />

   
</div>

<div>
    @Html.PagedListPager(Model, page => Url.Action("Index", new {page, pageSize = Model.PageSize }))
    Showing @Model.FirstItemOnPage to @Model.LastItemOnPage of @Model.TotalItemCount Records
</div>

}
else
{
    <p>
        No record found
    </p>
}